name: Assembly

on:
  push:
    paths:
      - asm/**
    branches: [ "main" ]
  pull_request:
    paths:
      - asm/**
    branches: [ "main" ]
  merge_group:
  workflow_dispatch:

jobs:
  compile:
    name: Compile ASM
    runs-on: ubuntu-latest

    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v4
      - name: Compile boot.asm
        working-directory: asm
        run: nasm -f bin boot.asm -o boot.bin
      - name: Check DOS/MBR boot sector
        id: bootsector
        run: echo "::set-output name=check::$(file ./asm/boot.bin)"
      - name: Validate the check
        run: echo ${{ steps.bootsector.outputs.check }} | grep -q "./asm/boot.bin: DOS/MBR boot sector"
