name: Rust

on:
  push:
#    paths:
#      - shell/**
    branches: [ "main" ]
  pull_request:
#    paths:
#      - shell/**
    branches: [ "main" ]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build hlshell
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build hlshell
        working-directory: shell
        run: cargo build --verbose

  lints:
    name: hlshell Lints
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@1.70
        with:
          components: rustfmt
      
      - name: Run cargo fmt on hlshell
        working-directory: shell
        run: cargo fmt --all --check

  tests:
    name: hlshell Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Run cargo tests
        working-directory: shell
        run: cargo test --verbose
