on:
  push:
    branches:
      - main

jobs:
  generate-con:
    name: Generate CONTRIBUTORS.svg
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p build

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          output: build/CONTRIBUTORS.svg
          avatarSize: 42

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
